/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialquiz;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author NAUFAL
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        setIcon();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtCloseAcc = new javax.swing.JButton();
        BtHomeAcc = new javax.swing.JButton();
        BtUserAcc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Info1 = new javax.swing.JTextField();
        Info3 = new javax.swing.JTextField();
        Info2 = new javax.swing.JTextField();
        BtSignout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 506));

        BtCloseAcc.setBackground(new java.awt.Color(24, 24, 24));
        BtCloseAcc.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\close.png")); // NOI18N
        BtCloseAcc.setBorder(null);
        BtCloseAcc.setContentAreaFilled(false);
        BtCloseAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtCloseAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCloseAccActionPerformed(evt);
            }
        });

        BtHomeAcc.setBackground(new java.awt.Color(24, 24, 24));
        BtHomeAcc.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\home.png")); // NOI18N
        BtHomeAcc.setBorder(null);
        BtHomeAcc.setContentAreaFilled(false);
        BtHomeAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtHomeAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHomeAccActionPerformed(evt);
            }
        });

        BtUserAcc.setBackground(new java.awt.Color(24, 24, 24));
        BtUserAcc.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\user putih.png")); // NOI18N
        BtUserAcc.setBorder(null);
        BtUserAcc.setContentAreaFilled(false);
        BtUserAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 196, 15));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACCOUNT");

        Info1.setEditable(false);
        Info1.setBackground(new java.awt.Color(50, 50, 50));
        Info1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        Info1.setForeground(new java.awt.Color(255, 255, 255));
        Info1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Info1.setText("Majhonny Khomar");
        Info1.setBorder(null);
        Info1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info1ActionPerformed(evt);
            }
        });
        Info1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Info1KeyReleased(evt);
            }
        });

        Info3.setEditable(false);
        Info3.setBackground(new java.awt.Color(50, 50, 50));
        Info3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        Info3.setForeground(new java.awt.Color(255, 255, 255));
        Info3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Info3.setText("Male");
        Info3.setBorder(null);
        Info3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Info3KeyReleased(evt);
            }
        });

        Info2.setEditable(false);
        Info2.setBackground(new java.awt.Color(50, 50, 50));
        Info2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        Info2.setForeground(new java.awt.Color(255, 255, 255));
        Info2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Info2.setText("March 21, 1998");
        Info2.setBorder(null);
        Info2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Info2KeyReleased(evt);
            }
        });

        BtSignout.setBackground(new java.awt.Color(241, 196, 15));
        BtSignout.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        BtSignout.setForeground(new java.awt.Color(24, 24, 24));
        BtSignout.setText("SIGN OUT");
        BtSignout.setBorder(null);
        BtSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSignoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtCloseAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtHomeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(508, 508, 508))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtUserAcc)
                                .addGap(159, 159, 159)
                                .addComponent(Info3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtCloseAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(BtHomeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BtUserAcc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Info3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(BtSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCloseAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCloseAccActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "  YAKIN INGIN KELUAR DARI SOCIAL QUIZ ?", "PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (n == JOptionPane.YES_OPTION){
            this.dispose();
            JOptionPane.showMessageDialog(this,"berhasil keluar");
        }
    }//GEN-LAST:event_BtCloseAccActionPerformed

    private void Info1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Info1KeyReleased
        
    }//GEN-LAST:event_Info1KeyReleased

    private void Info3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Info3KeyReleased
        
    }//GEN-LAST:event_Info3KeyReleased

    private void Info2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Info2KeyReleased
        
    }//GEN-LAST:event_Info2KeyReleased

    private void Info1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info1ActionPerformed

    private void BtHomeAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeAccActionPerformed
        this.dispose();
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_BtHomeAccActionPerformed

    private void BtSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSignoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_BtSignoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCloseAcc;
    private javax.swing.JButton BtHomeAcc;
    private javax.swing.JButton BtSignout;
    private javax.swing.JButton BtUserAcc;
    private javax.swing.JTextField Info1;
    private javax.swing.JTextField Info2;
    private javax.swing.JTextField Info3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
