/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialquiz;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author NAUFAL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setIcon();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EnterCode = new javax.swing.JTextField();
        BtPlay = new javax.swing.JButton();
        LbCode = new javax.swing.JLabel();
        BtUserHome = new javax.swing.JButton();
        BtHomeHome = new javax.swing.JButton();
        BtCloseHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 506));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 196, 15));
        jLabel2.setText("ENTER CODE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 170, -1, -1));

        EnterCode.setBackground(new java.awt.Color(50, 50, 50));
        EnterCode.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        EnterCode.setForeground(new java.awt.Color(255, 255, 255));
        EnterCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterCode.setBorder(null);
        EnterCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EnterCodeKeyReleased(evt);
            }
        });
        jPanel1.add(EnterCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 221, 354, 45));

        BtPlay.setBackground(new java.awt.Color(241, 196, 15));
        BtPlay.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        BtPlay.setForeground(new java.awt.Color(24, 24, 24));
        BtPlay.setText("PLAY");
        BtPlay.setBorder(null);
        BtPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPlayActionPerformed(evt);
            }
        });
        jPanel1.add(BtPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 372, 98, 35));

        LbCode.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        LbCode.setForeground(new java.awt.Color(169, 50, 38));
        LbCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LbCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 284, 176, 23));

        BtUserHome.setBackground(new java.awt.Color(24, 24, 24));
        BtUserHome.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\user.png")); // NOI18N
        BtUserHome.setBorder(null);
        BtUserHome.setContentAreaFilled(false);
        BtUserHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtUserHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUserHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BtUserHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        BtHomeHome.setBackground(new java.awt.Color(24, 24, 24));
        BtHomeHome.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\home putih.png")); // NOI18N
        BtHomeHome.setBorder(null);
        BtHomeHome.setContentAreaFilled(false);
        BtHomeHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtHomeHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHomeHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BtHomeHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 214, 44, 38));

        BtCloseHome.setBackground(new java.awt.Color(24, 24, 24));
        BtCloseHome.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\CCIT\\semester 2\\Project 1\\close.png")); // NOI18N
        BtCloseHome.setBorder(null);
        BtCloseHome.setContentAreaFilled(false);
        BtCloseHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtCloseHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCloseHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BtCloseHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, 44, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPlayActionPerformed
        if(EnterCode.getText().trim().isEmpty()){
            LbCode.setText("Kode Tidak Boleh Kosong");
        }
        this.dispose();
        Soal1 soal1 = new Soal1();
        soal1.setVisible(true);
        
    }//GEN-LAST:event_BtPlayActionPerformed

    private void EnterCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterCodeKeyReleased
        LbCode.setText("");
    }//GEN-LAST:event_EnterCodeKeyReleased

    private void BtCloseHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCloseHomeActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "  YAKIN INGIN KELUAR DARI SOCIAL QUIZ ?", "PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(n == JOptionPane.YES_OPTION){
            this.dispose();
            JOptionPane.showMessageDialog(this,"berhasil keluar");
        }
    }//GEN-LAST:event_BtCloseHomeActionPerformed

    private void BtUserHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUserHomeActionPerformed
        this.dispose();
        Account account = new Account();
        account.setVisible(true);
    }//GEN-LAST:event_BtUserHomeActionPerformed

    private void BtHomeHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtHomeHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCloseHome;
    private javax.swing.JButton BtHomeHome;
    private javax.swing.JButton BtPlay;
    private javax.swing.JButton BtUserHome;
    private javax.swing.JTextField EnterCode;
    private javax.swing.JLabel LbCode;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
