/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialquiz;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author NAUFAL
 */
public class Soal4 extends javax.swing.JFrame {

    /**
     * Creates new form Soal1
     */
    public int score4;
    public Soal4() {
        initComponents();
        
    }

    Soal4(int score3) {
        initComponents();
        setIcon();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        score4=score3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtCloseSoal = new javax.swing.JButton();
        BtHomeSoal = new javax.swing.JButton();
        Ans1 = new javax.swing.JButton();
        Ans3 = new javax.swing.JButton();
        Ans2 = new javax.swing.JButton();
        Ans4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));

        BtCloseSoal.setBackground(new java.awt.Color(24, 24, 24));
        BtCloseSoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socialquiz/close.png"))); // NOI18N
        BtCloseSoal.setBorder(null);
        BtCloseSoal.setContentAreaFilled(false);
        BtCloseSoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtCloseSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCloseSoalActionPerformed(evt);
            }
        });

        BtHomeSoal.setBackground(new java.awt.Color(24, 24, 24));
        BtHomeSoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socialquiz/home.png"))); // NOI18N
        BtHomeSoal.setBorder(null);
        BtHomeSoal.setContentAreaFilled(false);
        BtHomeSoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtHomeSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHomeSoalActionPerformed(evt);
            }
        });

        Ans1.setBackground(new java.awt.Color(50, 50, 50));
        Ans1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Ans1.setForeground(new java.awt.Color(255, 255, 255));
        Ans1.setText("Menolak keras budaya luar");
        Ans1.setBorder(null);
        Ans1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans1ActionPerformed(evt);
            }
        });

        Ans3.setBackground(new java.awt.Color(50, 50, 50));
        Ans3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Ans3.setForeground(new java.awt.Color(255, 255, 255));
        Ans3.setText("Menerima budaya luar ");
        Ans3.setBorder(null);
        Ans3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans3ActionPerformed(evt);
            }
        });

        Ans2.setBackground(new java.awt.Color(50, 50, 50));
        Ans2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Ans2.setForeground(new java.awt.Color(255, 255, 255));
        Ans2.setText("Selektif dalam memilih budaya");
        Ans2.setBorder(null);
        Ans2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans2ActionPerformed(evt);
            }
        });

        Ans4.setBackground(new java.awt.Color(50, 50, 50));
        Ans4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Ans4.setForeground(new java.awt.Color(255, 255, 255));
        Ans4.setText("Melestarikan budaya luar ");
        Ans4.setBorder(null);
        Ans4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ans4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ans4ActionPerformed(evt);
            }
        });

        Question1.setEditable(false);
        Question1.setBackground(new java.awt.Color(41, 38, 23));
        Question1.setColumns(20);
        Question1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        Question1.setForeground(new java.awt.Color(255, 255, 255));
        Question1.setRows(5);
        Question1.setText("\n4.bagaimana kita menyikapi dampak budaya\nluar yang sangat mudah diterima oleh\nkaum milenial?");
        Question1.setBorder(null);
        jScrollPane1.setViewportView(Question1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtCloseSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtHomeSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ans4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtCloseSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(BtHomeSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ans4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCloseSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCloseSoalActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "  YAKIN INGIN KELUAR DARI SOCIAL QUIZ ?", "PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(n == JOptionPane.YES_OPTION){
        
        this.dispose();
        JOptionPane.showMessageDialog(this,"berhasil keluar");
        }
    }//GEN-LAST:event_BtCloseSoalActionPerformed

    private void BtHomeSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeSoalActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "  YAKIN INGIN KEMBALI KE HOME ?", "PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(n == JOptionPane.YES_OPTION){
        
        this.dispose();
        Home home = new Home();
        home.setVisible(true);
        }
    }//GEN-LAST:event_BtHomeSoalActionPerformed

    private void Ans4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans4ActionPerformed
        score4=score4 + 0;
        this.dispose();
        Soal5 soal5 = new Soal5(score4);
        soal5.setVisible(true);
    }//GEN-LAST:event_Ans4ActionPerformed

    private void Ans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans2ActionPerformed
        score4 = score4 + 10;
        
        this.dispose();
        Soal5 soal5 = new Soal5(score4);
        soal5.setVisible(true);
    }//GEN-LAST:event_Ans2ActionPerformed

    private void Ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans1ActionPerformed
        score4= score4 + 0;
        this.dispose();
        Soal5 soal5 = new Soal5(score4);
        soal5.setVisible(true);
    }//GEN-LAST:event_Ans1ActionPerformed

    private void Ans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ans3ActionPerformed
        score4=score4 + 0;
        this.dispose();
        Soal5 soal5 = new Soal5(score4);
        soal5.setVisible(true);
    }//GEN-LAST:event_Ans3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ans1;
    private javax.swing.JButton Ans2;
    private javax.swing.JButton Ans3;
    private javax.swing.JButton Ans4;
    private javax.swing.JButton BtCloseSoal;
    private javax.swing.JButton BtHomeSoal;
    private javax.swing.JTextArea Question1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
